//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYJ.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class GOALACTUAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GOALACTUAL()
        {
            this.CHARTs = new HashSet<CHART>();
        }

        [DisplayName("Goal/Actual")]
        public int goalActualID { get; set; }
        [DisplayName("Goal")]
        public string goalValue { get; set; }
        [DisplayName("Actual")]
        public string actualGoal { get; set; }
        public Nullable<int> teamID { get; set; }
        public Nullable<int> workstreamID { get; set; }
        public Nullable<int> categoryID { get; set; }
        public Nullable<int> subcategoryID { get; set; }
        public Nullable<int> fiscalYearID { get; set; }
        public Nullable<int> quarteroptionID { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHART> CHARTs { get; set; }
        public virtual FISCALYEAR FISCALYEAR { get; set; }
        public virtual QUARTEROPTION QUARTEROPTION { get; set; }
        public virtual SUBCATEGORY SUBCATEGORY { get; set; }
        public virtual TEAM TEAM { get; set; }
        public virtual WORKSTREAM WORKSTREAM { get; set; }
        public virtual WORKSTREAM WORKSTREAM1 { get; set; }
    }
}
